http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
core.autocrlf=true
core.fscache=true
core.symlinks=true
user.name='parisotto'
user.email='parisotto@gmail.com'
core.editor=vim
filesystem.Oracle Corporation|1.8.0_191|2126842948.timestampresolution=1001 microseconds
filesystem.Oracle Corporation|1.8.0_191|2126842948.minracythreshold=0 nanoseconds
filesystem.Oracle Corporation|1.8.0_231|2126842948.timestampresolution=12001 microseconds
filesystem.Oracle Corporation|1.8.0_231|2126842948.minracythreshold=0 nanoseconds
gui.recentrepo=C:/Users/paris/git/repository
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filesystem.Oracle Corporation|1.8.0_241|2126842948.timestampresolution=1001 microseconds
filesystem.Oracle Corporation|1.8.0_241|2126842948.minracythreshold=0 nanoseconds
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=https://github.com/Parisotto/parisotto.github.io.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
credencial.username='Parisotto'
credential.username='parisotto'
